// This file was generated by RedwoodJS
import { RouteParams, QueryParams } from '@redwoodjs/router'
import { A } from 'ts-toolbelt'


declare module '@redwoodjs/router' {
  interface AvailableRoutes {
    // Only "<Route />" components with a "name" and "path" prop will be populated here.
    about: (params?: RouteParams<"/about"> & QueryParams) => "/about"
    home: (params?: RouteParams<"/"> & QueryParams) => "/"
    communityDetails: (params?: RouteParams<"/community-details"> & QueryParams) => "/community-details"
    communities: (params?: RouteParams<"/communities"> & QueryParams) => "/communities"
    gymDetails: (params?: RouteParams<"/gym-details"> & QueryParams) => "/gym-details"
    gyms: (params?: RouteParams<"/gyms"> & QueryParams) => "/gyms"
    profile: (params?: RouteParams<"/profile"> & QueryParams) => "/profile"
    dashboard: (params?: RouteParams<"/dashboard"> & QueryParams) => "/dashboard"
    signUp: (params?: RouteParams<"/sign-up"> & QueryParams) => "/sign-up"
    signIn: (params?: RouteParams<"/sign-in"> & QueryParams) => "/sign-in"
  }
}

