// This file was generated by RedwoodJS
import AboutPageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/AboutPage/AboutPage'
import CommunitiesPageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/CommunitiesPage/CommunitiesPage'
import CommunityDetailsPageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/CommunityDetailsPage/CommunityDetailsPage'
import DashboardPageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/DashboardPage/DashboardPage'
import FatalErrorPageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/FatalErrorPage/FatalErrorPage'
import ForgotPasswordPageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/ForgotPasswordPage/ForgotPasswordPage'
import GymDetailsPageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/GymDetailsPage/GymDetailsPage'
import GymsPageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/GymsPage/GymsPage'
import HomePageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/HomePage/HomePage'
import NotFoundPageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/NotFoundPage/NotFoundPage'
import ProfilePageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/ProfilePage/ProfilePage'
import SignInPageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/SignInPage/SignInPage'
import SignUpPageType from '/Users/martinfrommel/Documents/Projects/FootholdFinder/App/dev/web/src/pages/SignUpPage/SignUpPage'

declare global {
  const AboutPage: typeof AboutPageType
  const CommunitiesPage: typeof CommunitiesPageType
  const CommunityDetailsPage: typeof CommunityDetailsPageType
  const DashboardPage: typeof DashboardPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const ForgotPasswordPage: typeof ForgotPasswordPageType
  const GymDetailsPage: typeof GymDetailsPageType
  const GymsPage: typeof GymsPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
  const ProfilePage: typeof ProfilePageType
  const SignInPage: typeof SignInPageType
  const SignUpPage: typeof SignUpPageType
}
